[package]
name = "letui-core"
version = "0.3.5"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
taffy = { version = "0.9.1", default-features = false, features = [
  "std",
  "taffy_tree",
  "flexbox",
  "grid",
  "block_layout",
  "content_size",
] }
unicode-segmentation = "1.13.2"
unicode-width = "0.2.2"

[lib]
name = "letui_core"
crate-type = ["cdylib"]
